// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ7Ycd6pinA_20k97E9R6vTbY41BD0fn0',
    appId: '1:934990742462:web:198dfebf5ec3cb9eb82fef',
    messagingSenderId: '934990742462',
    projectId: 'diyotest-2c18d',
    authDomain: 'diyotest-2c18d.firebaseapp.com',
    storageBucket: 'diyotest-2c18d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBRrn0kwatV5NhnCl0gD3OzlkRAEQU8c',
    appId: '1:934990742462:android:800523102d4dc5beb82fef',
    messagingSenderId: '934990742462',
    projectId: 'diyotest-2c18d',
    storageBucket: 'diyotest-2c18d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBby2Th7muP57I6na2QZWQKMCbf7_eOr-c',
    appId: '1:934990742462:ios:424364aadc138d3db82fef',
    messagingSenderId: '934990742462',
    projectId: 'diyotest-2c18d',
    storageBucket: 'diyotest-2c18d.appspot.com',
    iosClientId: '934990742462-c0gukeor58n8bc20me3bibuau9a6a7pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBby2Th7muP57I6na2QZWQKMCbf7_eOr-c',
    appId: '1:934990742462:ios:424364aadc138d3db82fef',
    messagingSenderId: '934990742462',
    projectId: 'diyotest-2c18d',
    storageBucket: 'diyotest-2c18d.appspot.com',
    iosClientId: '934990742462-c0gukeor58n8bc20me3bibuau9a6a7pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diyo',
  );
}
